Test cases for a classloader leak in Glassfish
This issue affects Glassfish 3.1, 3.1.1b09 and 3.2b06 .
See: http://java.net/jira/browse/GLASSFISH-16917

It causes OutOfMemory exceptions referring to PermGen space
after repeated redeployments:

  java.lang.OutOfMemoryError: PermGen space

Learn more here:

  http://blog.ringerc.id.au/2011/06/java-ee-application-servers-learning.html